handle weird cases
Signed-off-by: Brady Pratt <bpratt@redhat.com>

diff --git a/task.yaml b/task.yaml
--- a/task.yaml
+++ b/task.yaml
@@ -36,6 +36,10 @@ spec:
           --output name \
           | cut -d/ -f2)
 
+        if [[ -z "${TASKRUN_NAME}" || "${TASKRUN_NAME}" =~ "No TaskRuns found" ]]; then
+          echo "Unable to find task for $(params.pipelinerun_name)" && exit 1
+        fi
+
         tkn taskrun logs \
           ${TASKRUN_NAME} \
           --step build \
@@ -62,16 +66,20 @@ spec:
 
         set -e
 
+        if [[ ! -f logs.txt ]]; then
+          echo "No build logs found" && exit 1
+        fi
+
         BUILD_OUTPUT=$(tail logs.txt)
 
-        QUERY='There has been a failed build! Help to understand the failure:
+        QUERY='There has been a failed build! Help to triage the failure:
 
         ${BUILD_OUTPUT}'
 
         echo "${QUERY}"
 
         curl \
-          --silent \
+          --fail-with-body \
           --insecure \
           --output response.json \
           --request POST \
@@ -80,5 +88,4 @@ spec:
           --data '{"query":"${QUERY}","stream":"false"}' \
           "${TANGERINE_API_URL}/assistants/$(params.tangerine_assistant_id)/chat"
 
-        # TODO: check for bad responses
         jq --raw-output .text_content response.json
